### ISSUE TITLE
创建ask的时候发生OOM

### ISSUE THREAD

**Issue by LiuJQ** [Tencent/soter#10]
> 如题，以下是堆栈日志信息
```java
java.lang.OutOfMemoryError: Failed to allocate a 570524220 byte allocation with 4182256 free bytes and 224MB until OOM
at android.security.keystore.SoterUtil.retriveJsonFromExportedData(SoterUtil.java:186)
at android.security.keystore.SoterUtil.getDataFromRaw(SoterUtil.java:154)
at android.security.keystore.SoterKeyStoreProvider.getAndroidKeyStorePublicKey(SoterKeyStoreProvider.java:139)
at android.security.keystore.SoterKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(SoterKeyStoreProvider.java:115)
at android.security.keystore.SoterKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(SoterKeyStoreProvider.java:125)
at android.security.keystore.SoterKeyStoreKeyPairRSAGeneratorSpi.generateKeyPair(SoterKeyStoreKeyPairRSAGeneratorSpi.java:348)
at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276)
at com.tencent.soter.core.SoterCore.generateAppGlobalSecureKey(SourceFile:122)
at com.tencent.soter.wrapper.wrap_key.SoterKeyGenerateEngine$1.run(SourceFile:111)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:207)
at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by yexuan910812** [comment]
需要确认几点：
1. 使用的soter-wrapper版本是多少？是否是1.3.8或以后？
2. 使用的手机型号是什么？

**Comment by LiuJQ** [comment]
@yexuan910812 

感谢回复，以下是具体信息：
```xml
compile 'com.tencent.soter:soter-wrapper:1.3.8.1'
```
设备信息
>Meizu U20，YunOS 5.1.1, flyme 6.1.0.0

**Comment by yexuan910812** [comment]
你好，这部设备我们查了下，不在支持列表中。可能是meizu在这部设备里带上了SOTER框架，但是本身没有设备密钥以及后台白名单。客户端Sample本身没有网络能力，因此没有做这项校验。在生产环境中使用SOTER时，请务必调用我们的后台接口查验设备是否在后台白名单中。

**Comment by LiuJQ** [comment]
@yexuan910812 

好的，谢谢，我们再调整下
