### ISSUE TITLE
华为手机必现认证失败，用的是2.1.8的sdk

### ISSUE THREAD

**Issue by VincentZhaoBing** [Tencent/soter#107]
soter: error in get auth key model
java.security.UnrecoverableKeyException: Failed to obtain X.509 form of public key
	at com.tencent.mm.security.keystore.SoterKeyStoreProvider.loadHwKeyStorePublicKeyFromKeystore(SoterKeyStoreProvider.java:350)
	at com.tencent.mm.security.keystore.soter.SoterKeyStoreSpi.engineGetKey(SoterKeyStoreSpi.java:37)
	at java.security.KeyStore.getKey(KeyStore.java:1062)
	at com.tencent.soter.core.sotercore.SoterCoreBeforeTreble.getAuthKeyModel(SoterCoreBeforeTreble.java:346)
	at com.tencent.soter.core.SoterCore.getAuthKeyModel(SoterCore.java:311)
	at com.tencent.soter.wrapper.wrap_task.TaskPrepareAuthKey.startUploadAuthKeyAfterGenerate(TaskPrepareAuthKey.java:158)
	at com.tencent.soter.wrapper.wrap_task.TaskPrepareAuthKey.access$300(TaskPrepareAuthKey.java:36)
	at com.tencent.soter.wrapper.wrap_task.TaskPrepareAuthKey$2.onSuccess(TaskPrepareAuthKey.java:151)
	at com.tencent.soter.wrapper.wrap_key.SoterKeyGenerateEngine.callback(SoterKeyGenerateEngine.java:172)
	at com.tencent.soter.wrapper.wrap_key.SoterKeyGenerateEngine.access$200(SoterKeyGenerateEngine.java:26)
	at com.tencent.soter.wrapper.wrap_key.SoterKeyGenerateEngine$1.run(SoterKeyGenerateEngine.java:145)
	at android.os.Handler.handleCallback(Handler.java:966)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.os.HandlerThread.run(HandlerThread.java:110)
Caused by: com.huawei.security.keystore.HwUniversalKeyStoreException: OK
	at com.huawei.security.HwKeystoreManager.getKeyStoreException(HwKeystoreManager.java:233)
	at com.tencent.mm.security.keystore.SoterKeyStoreProvider.loadHwKeyStorePublicKeyFromKeystore(SoterKeyStoreProvider.java:352)
	... 15 more

**Comment by HalfLike** [comment]
java.security.KeyStore.getKey(KeyStore.java:1062)

**Comment by HalfLike** [comment]
at com.tencent.mm.security.keystore.soter.SoterKeyStoreSpi.engineGetKey(SoterKeyStoreSpi.java:37)
at java.security.KeyStore.getKey(KeyStore.java:1062)

**Comment by HalfLike** [comment]
at com.tencent.mm.security.keystore.soter.SoterKeyStoreSpi.engineGetKey(SoterKeyStoreSpi.java:37)
at java.security.KeyStore.getKey(KeyStore.java:1062)
这里是手机系统的方法失败了，可以重启手机/更新系统，删除指纹/面容后，重新录入再尝试。如果还有问题，需要用户联系手机厂商反馈此问题。
