### ISSUE TITLE
Mi5出现OOM现象

### ISSUE THREAD

**Issue by wb1992321** [Tencent/soter#11]
# SoterGenKeyHandlerThreadName(1589)
java.lang.OutOfMemoryError
Failed to allocate a 570524220 byte allocation with 16777216 free bytes and 212MB until OOM
`

android.security.keystore.SoterUtil.retriveJsonFromExportedData(SoterUtil.java:189)
--
2 android.security.keystore.SoterUtil.getDataFromRaw(SoterUtil.java:152)
3 android.security.keystore.SoterKeyStoreProvider.getAndroidKeyStorePublicKey(SoterKeyStoreProvider.java:137)
4 android.security.keystore.SoterKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(SoterKeyStoreProvider.java:114)
5 android.security.keystore.SoterKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(SoterKeyStoreProvider.java:123)
6 android.security.keystore.SoterKeyStoreKeyPairRSAGeneratorSpi.generateKeyPair(SoterKeyStoreKeyPairRSAGeneratorSpi.java:364)
7 java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:699)
8 com.tencent.a.a.a.c(SourceFile:122)
9 com.tencent.a.b.d.b$1.run(SourceFile:111)
10 android.os.Handler.handleCallback(Handler.java:754)
11 android.os.Handler.dispatchMessage(Handler.java:95)
12 android.os.Looper.loop(Looper.java:160)
13 android.os.HandlerThread.run(HandlerThread.java:61)

`

**Comment by LiuJQ** [comment]
可以关注一下这个相关问题，#10 
在[支持机型列表](https://mp.weixin.qq.com/s/IRI-RCGsVB2WiPwUCGcytA)中也可查知小米5不支持soter

**Comment by yexuan910812** [comment]
你好，Mi 5不在支持列表中。在使用SOTER之前，需要从我们的后台接口确认这部机器是否支持SOTER。

**Comment by yangyueyue** [comment]
java.lang.AbstractMethodError: abstract method "void android.hardware.fingerprint.FingerprintManager

vivo x7当验证指纹成功之后，直接报错



10-14 15:58:29.343 4440-4440/com.womai E/womai_error: java.lang.AbstractMethodError: abstract method "void android.hardware.fingerprint.FingerprintManager$AuthenticationCallback.onAuthenticationSucceeded(android.hardware.fingerprint.FingerprintManager$AuthenticationResult)"
                                                          at android.hardware.fingerprint.FingerprintManager$MyHandler.sendAuthenticatedResult(FingerprintManager.java:919)
                                                          at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:761)
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:135)
                                                          at android.app.ActivityThread.main(ActivityThread.java:5400)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
10-14 15:58:29.353 4440-4440/com.womai E/getExternalStorage:    37  root=/storage/emulated/0
10-14 15:58:29.353 4440-4440/com.womai E/getExternalStorage: 41  root=/storage/emulated/0
10-14 15:58:29.353 4440-4440/com.womai E/getExternalStorage:    37  root=/storage/emulated/0
10-14 15:58:29.353 4440-4440/com.womai E/getExternalStorage: 41  root=/storage/emulated/0
10-14 15:58:29.353 4440-4440/com.womai E/Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.AbstractMethodError: abstract method "void android.hardware.fingerprint.FingerprintManager$AuthenticationCallback.onAuthenticationSucceeded(android.hardware.fingerprint.FingerprintManager$AuthenticationResult)"
                                                                     at android.hardware.fingerprint.FingerprintManager$MyHandler.sendAuthenticatedResult(FingerprintManager.java:919)
                                                                     at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:761)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5400)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
10-14 15:58:29.353 4440-4440/com.womai E/AndroidRuntime: FATAL EXCEPTION: main
                                                         Process: com.womai, PID: 4440
                                                         java.lang.AbstractMethodError: abstract method "void android.hardware.fingerprint.FingerprintManager$AuthenticationCallback.onAuthenticationSucceeded(android.hardware.fingerprint.FingerprintManager$AuthenticationResult)"
                                                             at android.hardware.fingerprint.FingerprintManager$MyHandler.sendAuthenticatedResult(FingerprintManager.java:919)
                                                             at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:761)
                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                             at android.os.Looper.loop(Looper.java:135)
                                                             at android.app.ActivityThread.main(ActivityThread.java:5400)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
