### ISSUE TITLE
OPPO Find X 无法使用人脸识别

### ISSUE THREAD

**Issue by whytot** [Tencent/soter#65]
使用微信可以用系统面部识别，但用soter写的demo无法使用

**Comment by whytot** [comment]
2020-06-12 11:01:04.961 20976-20976/? I/.fingerauthtes: Late-enabling -Xcheck:jni
2020-06-12 11:01:04.978 20976-20976/? E/.fingerauthtes: Unknown bits set in runtime_flags: 0x28000
2020-06-12 11:01:05.050 20976-20976/com.bill.fingerauthtest I/Perf: Connecting to perf service.
2020-06-12 11:01:05.064 20976-22566/com.bill.fingerauthtest I/Soter.SoterCore: soter: SoterCore is call static block to init SoterCore IMPL
2020-06-12 11:01:05.065 20976-22567/com.bill.fingerauthtest E/Perf: Fail to get file list com.bill.fingerauthtest
2020-06-12 11:01:05.066 20976-22567/com.bill.fingerauthtest E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2020-06-12 11:01:05.066 20976-22567/com.bill.fingerauthtest E/Perf: Fail to get file list com.bill.fingerauthtest
2020-06-12 11:01:05.066 20976-22566/com.bill.fingerauthtest I/Soter.SoterCoreBeforeTreble: soter: no SoterProvider found
2020-06-12 11:01:05.066 20976-22567/com.bill.fingerauthtest E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2020-06-12 11:01:05.067 20976-22566/com.bill.fingerauthtest I/Soter.SoterCore: soter: SoterCore is call static block to init SoterCore IMPL, IMPL is null[true]
2020-06-12 11:01:05.067 20976-22566/com.bill.fingerauthtest D/Soter.SoterCore: soter: getFingerprint  <deviceinfo><MANUFACTURER name="OPPO"><MODEL name="PAFM00"><VERSION_RELEASE name="10"><VERSION_INCREMENTAL name="1587089548"><DISPLAY name="PAFM00_11_F.10"></DISPLAY></VERSION_INCREMENTAL></VERSION_RELEASE></MODEL></MANUFACTURER></deviceinfo>
2020-06-12 11:01:05.069 20976-22566/com.bill.fingerauthtest D/Soter.SoterCore: soter: getFingerprint  <deviceinfo><MANUFACTURER name="OPPO"><MODEL name="PAFM00"><VERSION_RELEASE name="10"><VERSION_INCREMENTAL name="1587089548"><DISPLAY name="PAFM00_11_F.10"></DISPLAY></VERSION_INCREMENTAL></VERSION_RELEASE></MODEL></MANUFACTURER></deviceinfo>
2020-06-12 11:01:05.071 20976-22566/com.bill.fingerauthtest I/Soter.SoterCore: soter: SoterCore IMPL is null then call getProviderSoterCore to init
2020-06-12 11:01:05.071 20976-22566/com.bill.fingerauthtest I/Soter.SoterCoreBeforeTreble: soter: no SoterProvider found
2020-06-12 11:01:05.071 20976-22566/com.bill.fingerauthtest I/Soter.TaskInit: soter: is triggered OOM: true
2020-06-12 11:01:05.072 20976-22566/com.bill.fingerauthtest I/Soter.SoterCore: soter: SoterCore IMPL is null[true], after call getProviderSoterCore to init
2020-06-12 11:01:05.072 20976-22566/com.bill.fingerauthtest I/Soter.SoterCore: soter: SoterCore IMPL is null then call tryToInitSoterTreble to init
2020-06-12 11:01:05.073 20976-22566/com.bill.fingerauthtest I/Soter.SoterCoreTreble: soter: initSoter in
2020-06-12 11:01:05.073 20976-22566/com.bill.fingerauthtest I/Soter.SyncJob: doAsSyncJob
2020-06-12 11:01:05.073 20976-22566/com.bill.fingerauthtest I/Soter.SoterCoreTreble: soter: bindServiceIfNeeded try to bind
2020-06-12 11:01:05.081 20976-22566/com.bill.fingerauthtest I/Soter.SoterCoreTreble: soter: bindService binding is start 
2020-06-12 11:01:05.081 20976-22566/com.bill.fingerauthtest I/Soter.SoterCoreTreble: soter: initSoter binding
2020-06-12 11:01:05.147 20976-20976/com.bill.fingerauthtest W/.fingerauthtes: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2020-06-12 11:01:05.148 20976-20976/com.bill.fingerauthtest W/.fingerauthtes: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2020-06-12 11:01:05.181 20976-20976/com.bill.fingerauthtest D/WindowManager: Add to mViews: DecorView@1e636eb[MainActivity], this = android.view.WindowManagerGlobal@8832c48,pkg=com.bill.fingerauthtest
2020-06-12 11:01:05.193 20976-20976/com.bill.fingerauthtest I/Soter.SoterCoreTreble: soter: onServiceConnected
2020-06-12 11:01:05.194 20976-20976/com.bill.fingerauthtest I/Soter.SoterCoreTreble: soter: Binding is done - Service connected
2020-06-12 11:01:08.084 20976-22566/com.bill.fingerauthtest I/Soter.SoterCoreTreble: soter: initSoter finish
2020-06-12 11:01:08.085 20976-20976/com.bill.fingerauthtest E/ANR_LOG: >>> msg's executing time is too long
2020-06-12 11:01:08.085 20976-20976/com.bill.fingerauthtest E/ANR_LOG: Blocked msg = { when=-3s2ms what=0 target=android.app.ActivityThread$H callback=android.app.LoadedApk$ServiceDispatcher$RunConnection } , cost  = 2891 ms
2020-06-12 11:01:08.085 20976-20976/com.bill.fingerauthtest E/ANR_LOG: >>>Current msg List is:
2020-06-12 11:01:08.085 20976-20976/com.bill.fingerauthtest E/ANR_LOG: Current msg <1>  = { when=-2s929ms what=0 target=android.os.Handler callback=androidx.core.content.res.ResourcesCompat$FontCallback$2 }
2020-06-12 11:01:08.085 20976-20976/com.bill.fingerauthtest E/ANR_LOG: Current msg <2>  = { when=-2s928ms what=0 target=android.os.Handler callback=androidx.core.content.res.ResourcesCompat$FontCallback$2 }
2020-06-12 11:01:08.085 20976-20976/com.bill.fingerauthtest E/ANR_LOG: Current msg <3>  = { when=-2s921ms what=0 target=android.os.Handler callback=androidx.core.content.res.ResourcesCompat$FontCallback$2 }
2020-06-12 11:01:08.085 20976-22566/com.bill.fingerauthtest I/Soter.SoterCoreBeforeTreble: soter: no SoterProvider found
2020-06-12 11:01:08.086 20976-20976/com.bill.fingerauthtest E/ANR_LOG: Current msg <4>  = { when=-2s919ms what=0 target=android.os.Handler callback=androidx.core.content.res.ResourcesCompat$FontCallback$2 }
2020-06-12 11:01:08.086 20976-20976/com.bill.fingerauthtest E/ANR_LOG: Current msg <5>  = { when=-2s918ms what=0 target=android.os.Handler callback=androidx.core.content.res.ResourcesCompat$FontCallback$2 }
2020-06-12 11:01:08.086 20976-20976/com.bill.fingerauthtest E/ANR_LOG: Current msg <6>  = { when=-2s905ms what=0 target=android.view.ViewRootImpl$ViewRootHandler callback=android.view.ViewRootImpl$4 }
2020-06-12 11:01:08.086 20976-20976/com.bill.fingerauthtest E/ANR_LOG: Current msg <7>  = { when=-2s895ms barrier=0 }
2020-06-12 11:01:08.086 20976-20976/com.bill.fingerauthtest E/ANR_LOG: Current msg <8>  = { when=-2s779ms what=149 target=android.app.ActivityThread$H obj=android.os.BinderProxy@a72393b }
2020-06-12 11:01:08.086 20976-20976/com.bill.fingerauthtest E/ANR_LOG: Current msg <9>  = { when=-2s75ms what=0 target=android.app.ActivityThread$H callback=android.app.-$$Lambda$ActivityThread$A4ykhsPb8qV3ffTqpQDklHSMDJ0 }
2020-06-12 11:01:08.086 20976-20976/com.bill.fingerauthtest E/ANR_LOG: Current msg <10>  = { when=-1s2ms what=0 target=android.os.Handler callback=com.tencent.soter.core.sotercore.SoterCoreTreble$5 }
2020-06-12 11:01:08.086 20976-20976/com.bill.fingerauthtest E/ANR_LOG: >>>CURRENT MSG DUMP OVER<<<
2020-06-12 11:01:08.086 20976-22566/com.bill.fingerauthtest I/Soter.TaskInit: soter: is triggered OOM: true
2020-06-12 11:01:08.087 20976-22566/com.bill.fingerauthtest E/Soter.SoterCore: soter: isNativeSupportSoter return[true]
2020-06-12 11:01:08.088 20976-20976/com.bill.fingerauthtest I/Choreographer: Skipped 173 frames!  The application may be doing too much work on its main thread.
2020-06-12 11:01:08.089 20976-22566/com.bill.fingerauthtest I/Soter.TaskInit: soter: is triggered OOM: true
2020-06-12 11:01:08.089 20976-22566/com.bill.fingerauthtest E/Soter.SoterCore: soter: isNativeSupportSoter return[true]
2020-06-12 11:01:08.091 20976-22566/com.bill.fingerauthtest I/Soter.TaskInit: soter: is triggered OOM: true
2020-06-12 11:01:08.092 20976-22566/com.bill.fingerauthtest E/Soter.SoterCore: soter: isNativeSupportSoter return[true]
2020-06-12 11:01:08.097 20976-22566/com.bill.fingerauthtest W/SystemServiceRegistry: No service published for: fingerprint
2020-06-12 11:01:08.099 20976-22566/com.bill.fingerauthtest E/Soter.FingerprintManagerProxy: soter: fingerprint manager is null in isHardwareDetected! Should never happen
2020-06-12 11:01:08.099 20976-22566/com.bill.fingerauthtest E/Soter.SoterCore: soter: isSupportFingerprint return[false]
2020-06-12 11:01:08.100 20976-22566/com.bill.fingerauthtest W/.fingerauthtes: Accessing hidden method Lcom/tencent/soter/core/biometric/FaceManager;->authenticate(Lcom/tencent/soter/core/biometric/FaceManager$CryptoObject;Landroid/os/CancellationSignal;ILcom/tencent/soter/core/biometric/FaceManager$AuthenticationCallback;Landroid/os/Handler;)V (blacklist, linking, denied)
2020-06-12 11:01:08.100 20976-22566/com.bill.fingerauthtest W/.fingerauthtes: Accessing hidden method Lcom/tencent/soter/core/biometric/FaceManager;->getBiometricName(Landroid/content/Context;)Ljava/lang/String; (blacklist, linking, denied)
2020-06-12 11:01:08.101 20976-22566/com.bill.fingerauthtest W/.fingerauthtes: Accessing hidden method Lcom/tencent/soter/core/biometric/FaceManager;->hasEnrolledFaces()Z (blacklist, linking, denied)
2020-06-12 11:01:08.101 20976-22566/com.bill.fingerauthtest W/.fingerauthtes: Accessing hidden method Lcom/tencent/soter/core/biometric/FaceManager;->isHardwareDetected()Z (blacklist, linking, denied)
2020-06-12 11:01:08.101 20976-22566/com.bill.fingerauthtest W/.fingerauthtes: Accessing hidden method Lcom/tencent/soter/core/biometric/FaceManager$CryptoObject;->getCipher()Ljavax/crypto/Cipher; (blacklist, linking, denied)
2020-06-12 11:01:08.101 20976-22566/com.bill.fingerauthtest W/.fingerauthtes: Accessing hidden method Lcom/tencent/soter/core/biometric/FaceManager$CryptoObject;-><init>(Ljavax/crypto/Cipher;)V (blacklist, linking, denied)
2020-06-12 11:01:08.101 20976-22566/com.bill.fingerauthtest W/.fingerauthtes: Accessing hidden method Lcom/tencent/soter/core/biometric/FaceManager$CryptoObject;-><init>(Ljava/security/Signature;)V (blacklist, linking, denied)
2020-06-12 11:01:08.101 20976-22566/com.bill.fingerauthtest W/.fingerauthtes: Accessing hidden method Lcom/tencent/soter/core/biometric/FaceManager$CryptoObject;-><init>(Ljavax/crypto/Mac;)V (blacklist, linking, denied)
2020-06-12 11:01:08.102 20976-22566/com.bill.fingerauthtest W/.fingerauthtes: Accessing hidden method Lcom/tencent/soter/core/biometric/SoterFaceManagerFactory;->getFaceManager(Landroid/content/Context;)Lcom/tencent/soter/core/biometric/FaceManager; (blacklist, reflection, denied)
2020-06-12 11:01:08.102 20976-22566/com.bill.fingerauthtest E/Soter.FaceidManagerProxy: soter: FaceManager init failed, maybe not support.java.lang.NoSuchMethodException: com.tencent.soter.core.biometric.SoterFaceManagerFactory.getFaceManager [class android.content.Context]
2020-06-12 11:01:08.103 20976-22566/com.bill.fingerauthtest W/System.err: java.lang.NoSuchMethodException: com.tencent.soter.core.biometric.SoterFaceManagerFactory.getFaceManager [class android.content.Context]
2020-06-12 11:01:08.103 20976-22566/com.bill.fingerauthtest W/System.err:     at java.lang.Class.getMethod(Class.java:2072)
2020-06-12 11:01:08.103 20976-22566/com.bill.fingerauthtest W/System.err:     at java.lang.Class.getDeclaredMethod(Class.java:2050)
2020-06-12 11:01:08.103 20976-22566/com.bill.fingerauthtest W/System.err:     at com.tencent.soter.core.biometric.FaceidManagerProxy.getFaceManager(FaceidManagerProxy.java:49)
2020-06-12 11:01:08.103 20976-22566/com.bill.fingerauthtest W/System.err:     at com.tencent.soter.core.biometric.FaceidManagerProxy.isHardwareDetected(FaceidManagerProxy.java:81)
2020-06-12 11:01:08.103 20976-22566/com.bill.fingerauthtest W/System.err:     at com.tencent.soter.core.biometric.BiometricManagerCompat$FaceidManagerImpl.isHardwareDetected(BiometricManagerCompat.java:517)
2020-06-12 11:01:08.104 20976-22566/com.bill.fingerauthtest W/System.err:     at com.tencent.soter.core.biometric.BiometricManagerCompat.isHardwareDetected(BiometricManagerCompat.java:118)
2020-06-12 11:01:08.104 20976-22566/com.bill.fingerauthtest W/System.err:     at com.tencent.soter.core.SoterCore.isSupportBiometric(SoterCore.java:468)
2020-06-12 11:01:08.104 20976-22566/com.bill.fingerauthtest W/System.err:     at com.tencent.soter.wrapper.wrap_task.TaskInit.<init>(TaskInit.java:125)
2020-06-12 11:01:08.104 20976-22566/com.bill.fingerauthtest W/System.err:     at com.tencent.soter.wrapper.SoterWrapperApi$1.run(SoterWrapperApi.java:65)
2020-06-12 11:01:08.104 20976-22566/com.bill.fingerauthtest W/System.err:     at android.os.Handler.handleCallback(Handler.java:883)
2020-06-12 11:01:08.104 20976-22566/com.bill.fingerauthtest W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
2020-06-12 11:01:08.104 20976-22566/com.bill.fingerauthtest W/System.err:     at android.os.Looper.loop(Looper.java:227)
2020-06-12 11:01:08.104 20976-22566/com.bill.fingerauthtest W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67)
2020-06-12 11:01:08.105 20976-22566/com.bill.fingerauthtest E/Soter.FaceidManagerProxy: soter: facemanager is null in isHardwareDetected! Should never happen
2020-06-12 11:01:08.105 20976-22566/com.bill.fingerauthtest E/Soter.SoterCore: soter: isSupportBiometric type[2] return[false]
2020-06-12 11:01:08.107 20976-22566/com.bill.fingerauthtest W/Soter.TaskInit: soter: it is strongly recommended to check device support from server, so you'd better provider a net wrapper to check it
2020-06-12 11:01:08.109 20976-22566/com.bill.fingerauthtest D/Soter.TaskInit: soter: ask status: -1
2020-06-12 11:01:08.110 20976-22566/com.bill.fingerauthtest I/Soter.SoterCoreTreble: soter: hasAppGlobalSecureKey in
2020-06-12 11:01:08.110 20976-22566/com.bill.fingerauthtest I/Soter.TaskInit: soter: is triggered OOM: true
2020-06-12 11:01:08.111 20976-22566/com.bill.fingerauthtest D/Soter.SoterCoreTreble: no need rebind
2020-06-12 11:01:08.112 20976-22570/com.bill.fingerauthtest I/AdrenoGLES: QUALCOMM build                   : 7d8d15e, I0e419467bc
    Build Date                       : 12/12/19
    OpenGL ES Shader Compiler Version: EV031.27.05.02
    Local Branch                     : 
    Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.8.3.R1.10.00.00.520.063
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
2020-06-12 11:01:08.112 20976-22570/com.bill.fingerauthtest I/AdrenoGLES: Build Config                     : S P 8.0.11 AArch64
2020-06-12 11:01:08.115 20976-22570/com.bill.fingerauthtest I/AdrenoGLES: PFP: 0x016ee187, ME: 0x00000000
2020-06-12 11:01:08.110 20976-20976/com.bill.fingerauthtest W/RenderThread: type=1400 audit(0.0:56334): avc: denied { search } for name="kgsl-3d0" dev="sysfs" ino=48782 scontext=u:r:untrusted_app:s0:c15,c257,c512,c768 tcontext=u:object_r:sysfs_kgsl:s0 tclass=dir permissive=0
2020-06-12 11:01:08.116 20976-22570/com.bill.fingerauthtest W/AdrenoUtils: <ReadGpuID_from_sysfs:194>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
2020-06-12 11:01:08.116 20976-22570/com.bill.fingerauthtest W/AdrenoUtils: <ReadGpuID:218>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
2020-06-12 11:01:08.118 20976-22566/com.bill.fingerauthtest D/Soter.TaskInit: soter: Wechatuid10271__scene8 status: 0
2020-06-12 11:01:08.118 20976-22566/com.bill.fingerauthtest W/Soter.TaskInit: soter: TaskInit check isNativeSupport[false]
2020-06-12 11:01:08.118 20976-22566/com.bill.fingerauthtest I/Soter.SoterTaskManager: soter: removing task: 60925586
2020-06-12 11:01:08.143 20976-22570/com.bill.fingerauthtest W/Gralloc3: mapper 3.x is not supported
2020-06-12 11:01:08.195 20976-22570/com.bill.fingerauthtest I/OpenGLRenderer: Davey! duration=2991ms; Flags=1, IntendedVsync=120868612946817, Vsync=120871496280035, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=120871497871493, AnimationStart=120871498071701, PerformTraversalsStart=120871498075503, DrawStart=120871546984358, SyncQueued=120871550347847, SyncStart=120871550873628, IssueDrawCommandsStart=120871550940347, SwapBuffers=120871603471076, FrameCompleted=120871604647274, DequeueBufferDuration=90000, QueueBufferDuration=751000, 
2020-06-12 11:01:08.216 20976-20976/com.bill.fingerauthtest I/Choreographer: Skipped 7 frames!  The application may be doing too much work on its main thread.
2020-06-12 11:01:08.227 20976-20976/com.bill.fingerauthtest E/SoterAuthManager: init onResult: SoterCoreResult{errCode=2, errMsg='device not support soter'}
2020-06-12 11:01:08.228 20976-20976/com.bill.fingerauthtest I/Soter.SoterWrapperApi: soter: starting prepare auth key: 0
2020-06-12 11:01:08.228 20976-20976/com.bill.fingerauthtest W/Soter.TaskPrepareAuthKey: soter: not support soter
2020-06-12 11:01:08.229 20976-20976/com.bill.fingerauthtest I/Soter.SoterTaskManager: soter: removing task: 91078284
2020-06-12 11:01:08.229 20976-20976/com.bill.fingerauthtest I/Soter.SoterTaskManager: soter: no such task: 91078284. maybe this task did not pass preExecute
2020-06-12 11:01:08.229 20976-20976/com.bill.fingerauthtest D/Soter.SoterTaskManager: soter: prepare eat execute.
2020-06-12 11:01:08.229 20976-20976/com.bill.fingerauthtest D/Soter.SoterWrapperApi: soter: add prepareAuthKey task failed.
2020-06-12 11:01:08.232 20976-20976/com.bill.fingerauthtest E/SoterAuthManager: prepareAuthKey onResult: SoterCoreResult{errCode=2, errMsg='device not support soter'}

**Comment by whytot** [comment]
api 版本2.0.4

**Comment by liuxb-tofu** [comment]
请问系统是什么版本呢？

**Comment by huma8848888** [comment]
+1，同样测试findx手机无法人脸识别

**Comment by liuxb-tofu** [comment]
> +1，同样测试findx手机无法人脸识别

是Android Q版本吗

**Comment by huma8848888** [comment]
> > +1，同样测试findx手机无法人脸识别
> 
> 是Android Q版本吗

android10 colorOS V7.0

**Comment by liuxb-tofu** [comment]
这个问题，oppo会在近期版本修复
