### ISSUE TITLE
soter 快速接入的方式，在华为 mater 20 pro 上报错 

### ISSUE THREAD

**Issue by peienliudao** [Tencent/soter#93]
soter 快速接入的方式，在华为 mater 20 pro 上报错 

 java.lang.NoSuchMethodError: No virtual method c()Z in class Lcom/tencent/soter/core/biometric/FaceManager; or its super classes (declaration of 'com.tencent.soter.core.biometric.FaceManager' appears in /system/framework/hwPartSecurity.jar)

 at com.tencent.soter.core.biometric.FaceidManagerProxy.d(FaceidManagerProxy.java:2)
        at com.tencent.soter.core.biometric.BiometricManagerCompat$FaceidManagerImpl.b(BiometricManagerCompat.java:1)
        at com.tencent.soter.core.biometric.BiometricManagerCompat.f(BiometricManagerCompat.java:3)
        at com.tencent.soter.core.SoterCore.s(SoterCore.java:1)
        at com.tencent.soter.wrapper.wrap_task.TaskInit.<init>(TaskInit.java:15)
        at com.tencent.soter.wrapper.SoterWrapperApi$1.run(SoterWrapperApi.java:1)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by peienliudao** [comment]
![image](https://user-images.githubusercontent.com/11829409/129698177-c2c8418d-68ff-49c9-84a6-86e9356fda2a.png)

**Comment by peienliudao** [comment]
![image](https://user-images.githubusercontent.com/11829409/129698661-f5b6657e-0d50-4b95-a586-010ae40a1acc.png)

**Comment by weiaiSanli** [comment]
相同的问题！

**Comment by weiaiSanli** [comment]
java.lang.NoSuchMethodError: No virtual method generateCertificateWithFakeSignature(Ljava/security/PublicKey;I)Ljava/security/cert/X509Certificate; in class Lcom/huawei/security/keystore/HwUniversalKeyStoreCertificateGenerator; or its super classes (declaration of 'com.huawei.security.keystore.HwUniversalKeyStoreCertificateGenerator' appears in /system/framework/hwEmui.jar)
01-17 11:17:42.701  1731  2176 E HYError : 	at com.huawei.security.keystore.HwUniversalKeyStoreKeyPairGeneratorSpi.generateSelfSignedCertificateWithFakeSignature(HwUniversalKeyStoreKeyPairGeneratorSpi.java:669)
01-17 11:17:42.701  1731  2176 E HYError : 	at com.huawei.security.keystore.HwUniversalKeyStoreKeyPairGeneratorSpi.generateSelfSignedCertificate(HwUniversalKeyStoreKeyPairGeneratorSpi.java:630)
01-17 11:17:42.701  1731  2176 E HYError : 	at com.huawei.security.keystore.HwUniversalKeyStoreKeyPairGeneratorSpi.generateSelfSignedCertificateBytes(HwUniversalKeyStoreKeyPairGeneratorSpi.java:614)
01-17 11:17:42.701  1731  2176 E HYError : 	at com.huawei.security.keystore.HwUniversalKeyStoreKeyPairGeneratorSpi.createCertificateChainBytes(HwUniversalKeyStoreKeyPairGeneratorSpi.java:609)
01-17 11:17:42.701  1731  2176 E HYError : 	at com.huawei.security.keystore.HwUniversalKeyStoreKeyPairGeneratorSpi.generateKeyPair(HwUniversalKeyStoreKeyPairGeneratorSpi.java:513)
01-17 11:17:42.701  1731  2176 E HYError : 	at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727)
01-17 11:17:42.701  1731  2176 E HYError : 	at com.tencent.soter.core.sotercore.SoterCoreBeforeTreble.generateAuthKey(SourceFile:228)
01-17 11:17:42.701  1731  2176 E HYError : 	at com.tencent.soter.core.SoterCore.generateAuthKey(SourceFile:250)
01-17 11:17:42.701  1731  2176 E HYError : 	at com.tencent.soter.wrapper.wrap_key.SoterKeyGenerateEngine$1.run(SourceFile:138)
01-17 11:17:42.701  1731  2176 E HYError : 	at android.os.Handler.handleCallback(Handler.java:955)
01-17 11:17:42.701  1731  2176 E HYError : 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-17 11:17:42.701  1731  2176 E HYError : 	at android.os.Looper.loopOnce(Looper.java:205)
01-17 11:17:42.701  1731  2176 E HYError : 	at android.os.Looper.loop(Looper.java:293)
01-17 11:17:42.701  1731  2176 E HYError : 	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by weiaiSanli** [comment]
应该是鸿蒙系统适配问题导致的，使用的为鸿蒙3.0系统

**Comment by gitboylovegirl** [comment]
还有维护吗 这个仓库
