### ISSUE TITLE
厂商反馈崩溃初步定位Soter

### ISSUE THREAD

**Issue by dengtuo** [Tencent/soter#96]
Soter开发者你们好，我们适配厂商包的时候，厂商反馈一下崩溃堆栈。希望排查一下，谢谢。

01-17 11:17:42.691  1731  2176 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method generateCertificateWithFakeSignature(Ljava/security/PublicKey;I)Ljava/security/cert/X509Certificate; in class Lcom/huawei/security/keystore/HwUniversalKeyStoreCertificateGenerator; or its super classes (declaration of 'com.huawei.security.keystore.HwUniversalKeyStoreCertificateGenerator' appears in /system/framework/hwEmui.jar)
01-17 11:17:42.691  1731  2176 E AndroidRuntime: 	at com.huawei.security.keystore.HwUniversalKeyStoreKeyPairGeneratorSpi.generateSelfSignedCertificateWithFakeSignature(HwUniversalKeyStoreKeyPairGeneratorSpi.java:669)
01-17 11:17:42.691  1731  2176 E AndroidRuntime: 	at com.huawei.security.keystore.HwUniversalKeyStoreKeyPairGeneratorSpi.generateSelfSignedCertificate(HwUniversalKeyStoreKeyPairGeneratorSpi.java:630)
01-17 11:17:42.691  1731  2176 E AndroidRuntime: 	at com.huawei.security.keystore.HwUniversalKeyStoreKeyPairGeneratorSpi.generateSelfSignedCertificateBytes(HwUniversalKeyStoreKeyPairGeneratorSpi.java:614)
01-17 11:17:42.691  1731  2176 E AndroidRuntime: 	at com.huawei.security.keystore.HwUniversalKeyStoreKeyPairGeneratorSpi.createCertificateChainBytes(HwUniversalKeyStoreKeyPairGeneratorSpi.java:609)
01-17 11:17:42.691  1731  2176 E AndroidRuntime: 	at com.huawei.security.keystore.HwUniversalKeyStoreKeyPairGeneratorSpi.generateKeyPair(HwUniversalKeyStoreKeyPairGeneratorSpi.java:513)
01-17 11:17:42.691  1731  2176 E AndroidRuntime: 	at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727)
01-17 11:17:42.691  1731  2176 E AndroidRuntime: 	at com.tencent.soter.core.sotercore.SoterCoreBeforeTreble.generateAuthKey(SourceFile:228)
01-17 11:17:42.691  1731  2176 E AndroidRuntime: 	at com.tencent.soter.core.SoterCore.generateAuthKey(SourceFile:250)
01-17 11:17:42.691  1731  2176 E AndroidRuntime: 	at com.tencent.soter.wrapper.wrap_key.SoterKeyGenerateEngine$1.run(SourceFile:138)
01-17 11:17:42.691  1731  2176 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:955)
01-17 11:17:42.691  1731  2176 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-17 11:17:42.691  1731  2176 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
01-17 11:17:42.691  1731  2176 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:293)
01-17 11:17:42.691  1731  2176 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
01-17 11:17:42.692  1661  2590 I WindowManager: Checking 1 opening apps (frozen=false timeout=false)...

**Comment by weiaiSanli** [comment]
荣耀3.0系统的bug，开发者能适配吗，我们只能先移除这个库了！

**Comment by weiaiSanli** [comment]
鸿蒙3.0系统的bug，开发者能适配吗，我们只能先移除这个库了！

**Comment by dengtuo** [comment]
> 鸿蒙3.0系统的bug，开发者能适配吗，我们只能先移除这个库了！

你们是当前直接移除了？

**Comment by weiaiSanli** [comment]
> > 鸿蒙3.0系统的bug，开发者能适配吗，我们只能先移除这个库了！
> 
> 你们是当前直接移除了？

不是，我们原来用的是2.0.6版本，升级到2.0.7解决了这个问题！你可以试一下～

**Comment by dengtuo** [comment]
> 

好的谢谢了，我升级一下
